### ISSUE TITLE
Complete steps -TypeError: recipe.recipeTags.join is not a function

### ISSUE THREAD

**Issue by chueny** [PeterBaker644/Recipe-Journal#44] opened 2020-09-08 17:38 UTC
TypeError: recipe.recipeTags.join is not a function

CardComplete
src/component/CreateRecipe/CardComplete.js:14
  11 | <h1 className="display-2 font-brand-small mb-0">{recipe.recipeName}</h1>
  12 | <hr className="divider-color" />
  13 | <span className="font-book text-center">{recipe.recipeDescription}</span>
> 14 | <span className="text-smaller font-book-italic text-truncate divider m-2 mb-3">
     | ^  15 |     Tags: {recipe.recipeTags.join(", ")}
  16 | </span>
  17 | <h4 className="rb-btn">Ingredients</h4>

**Comment by PeterBaker644** [comment] 2020-09-08 17:44
Duplicate of #29.

**Closed by PeterBaker644** 2020-09-08 17:44 UTC
Labels: duplicate
